config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get '/about', to: 'homes#about', as: 'about'
    get "search" => "searches#search"
    resources :items, only: [:index,:show] do
      resource :favorites, only: [:create,:destroy]
    end
    resources :favorites, only: [:index]
    get '/users/my_page', to: 'users#show', as: 'my_page'
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all', as: 'cart_items_destroy_all'
    resources :cart_items, except: [:show,:new,:edit]
    post 'orders/confirm', to: 'orders#confirm', as: 'orders_confirm'
    get 'orders/complete', to: 'orders#complete', as: 'orders_complete'
    resources :orders, except: [:edit,:destroy]
    resources :genres, only: [:show]
    resources :tags, only: [:show]
    resources :admins, only: [:index,:show]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'users_guest_sign_in'
  end

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

# 管理者用

  namespace :admin do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :items, except: [:destroy]
    resources :genres, except: [:new,:destroy]
    resources :tags, except: [:new,:show,:destroy]
    get 'users/:id/order_history', to: 'users#order_history', as: 'users_order_history'
    patch 'users/:id/deactivate', to: 'users#deactivate', as: 'users_deactivate'
    resources :users, except: [:new,:create,:destroy]
    patch 'admins/:id/deactivate', to: 'admins#deactivate', as: 'admins_deactivate'
    resources :admins, except: [:new,:create,:destroy]
    resources :orders, only: [:index,:show,:update]
    resources :order_items, only: [:update]
  end

  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in', as: 'admins_guest_sign_in'
  end

  devise_for :admin,skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre
  has_many :order_items, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :introduction, presence: true
  validates :detail, presence: true
  validates :price_without_tax, presence: true
  validates :is_stopped, inclusion: {in: [true, false]}
  validate :image_type


  def price_with_tax
    tax = 1 + 0.10
    ( self.price_without_tax * tax).floor
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def save_tags(save_item_tags)
    current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
    old_tags = current_tags - save_item_tags
    new_tags = save_item_tags - current_tags

    old_tags.each do |old_name|
      self.tags.delete Tag.find_by(tag_name: old_name)
    end

    new_tags.each do |new_name|
      item_tag = Tag.find_or_create_by(tag_name: new_name)
      self.tags << item_tag
    end
  end

  def self.search(word)
    if word != ""
      Item.eager_load(:tags).where(['name LIKE ? OR introduction LIKE ? OR tags.tag_name LIKE ?', "%#{word}%", "%#{word}%", "%#{word}%" ])
      #部分一致で検索
    else
      Item.order('created_at DESC')
    end
  end
  
  def favorited_by?(user)
    favorites.where(user_id: user).exists?
  end

private

  def image_type
    if !image.blob
      errors.add(:image, 'をアップロードしてください')
    elsif !image.blob.content_type.in?(%('image/jpeg image/png'))
      errors.add(:image, 'はJPEGまたはPNG形式を選択してアップロードしてください')
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_guest_user, except: [:index, :show, :edit, :new]

  def index
    @items = Item.page(params[:page]).per(8)
    @total_items = Item.all
    @genres = Genre.all
  end

  def new
    @item_new = Item.new
    @genres = Genre.all
    @tags = Tag.all
  end

  def create
    @item_new = Item.new(item_params)
    tag_list = params[:item][:tag_ids].split(',')
    if @item_new.save
      @item_new.save_tags(tag_list)
      flash[:notice] = "商品を登録しました"
      redirect_to admin_item_path(@item_new)
    else
      flash[:alert] = "商品の登録に失敗しました"
      @genres = Genre.all
      @tags = Tag.all
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @tag_list =@item.tags.pluck(:tag_name).join(",")
    @genres = Genre.all
    @tags = Tag.all
  end

  def update
    @item = Item.find(params[:id])
    tag_list = params[:item][:tag_ids].split(',')
    if @item.update(item_params)
      @item.save_tags(tag_list)
      flash[:notice] = "商品情報を変更しました"
      redirect_to admin_item_path(@item)
    else
      # DBエラ－対策
      @item_old_image = Item.find(params[:id])
      @genres = Genre.all
      @tags = Tag.all
      flash[:alert] = "商品情報の変更に失敗しました"
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price_without_tax, :is_stopped, :detail, :image, tag_ids: [])
  end

  def ensure_guest_user
    @admin = current_admin
    if @admin.login_id == "guest@example"
      flash[:alert] = "ゲストユーザーはアクセスできません"
      redirect_to admin_root_path
    end
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_index.html.erb
<table class="table mt-3 mb-5">
  <thead style="background-color:#f5fffa">
    <tr>
      <th>商品ID</th>
      <th></th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
    <tr>
      <td><%= item.id %></td>
      <td><%= image_tag item.get_image(50, 50) %></td>
      <td><%= link_to item.name, admin_item_path(item) %></td>
      <td><%= item.price_without_tax.to_s(:delimited) %></td>
      <td><%= item.genre.name %></td>
      <% if item.is_stopped == false %>
        <td class="text-success">販売中</td>
      <% else %>
        <td class="text-black-50">販売停止中</td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="mb-3">
  <%= paginate @items %>
</div>

app/views/admin/items/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <h2>商品編集</h2>
      <div class="row-md-10 pb-3">
        <%= render 'layouts/errors', obj: @item %>
        <%= form_with model: @item, url: admin_item_path(@item), method: :patch, local: true do |f| %>
          <div class="field d-flex mb-3">
            <div class="w-25">商品画像</div>
            <!--画像プレビュー機能によるDB保存エラー回避のために記載-->
            <% if @item_old_image %>
              <%= image_tag @item_old_image.get_image(300,200) %>
            <% elsif @item.image.attached? %>
              <%= image_tag @item.get_image(300,200) %>
            <% end %>
          </div>
          <div class="field d-flex mb-3">
            <div class="w-25"></div>
            <div id="preview"></div>
          </div>
          <div class="field d-flex mb-3">
            <%= f.label :image, "画像を変更する", class: "w-25" %><br>
            <%= f.file_field :image, accept:'image/*', id:"item-image" %>
          </div>
          <div class="field d-flex mb-3">
            <%= f.label :name, "商品名", class: "w-25" %><br>
            <%= f.text_field :name, class: "form-control w-50" %>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :introduction, "商品説明", class: "w-25" %><br>
            <%= f.text_area :introduction, class: "form-control w-50" %>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :detail, "詳細", class: "w-25" %><br>
            <%= f.text_area :detail, class: "form-control w-50" %>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :genre_id, "ジャンル", class: "w-25" %><br>
            <%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "選択して下さい", class: "form-select w-50" %>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :tag_ids, "検索用タグ", class: "w-25" %><br>
            <%= f.text_field :tag_ids, value: @tag_list, placeholder: "タグを複数つけるには','で区切ってください。", :required => true, class: "form-control w-50" %>
          </div>

          <div class="d-flex flex-wrap">
            <div class="w-25 mb-3">既存のタグ一覧</div>
            <div class="w-50 mb-3">
              <% @tags.each do |tag| %>
                <i class="fa-solid fa-tag p-1 mb-3"></i><%= tag.tag_name %>
              <% end %>
            </div>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :price_without_tax, "税抜価格", class: "w-25" %><br>
            <%= f.number_field :price_without_tax, class: "w-50" %>円
          </div>

          <div class="field d-flex mb-3">
            <p class="w-25">販売ステータス</p>
            <div class="is_stopped">
              <%= f.radio_button :is_stopped, false %>
              <%= f.label :is_stopped, "販売中", value: false %>
              <%= f.radio_button :is_stopped, true, class: "ml-3"%>
              <%= f.label :is_stopped, "販売停止中", value: true %>
            </div>
          </div>

          <div class="actions text-center mb-5">
            <%= f.submit "変更を保存", class: 'btn btn-success w-50' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-3">
      <%= render 'layouts/sidebar',genres: @genres %>
    </div>
    <div class="col-md-9 mx-auto">
      <div class="row-md-9 pb-3">
        <div class="d-flex">
          <h2 class="mr-auto">商品一覧（全<%= @total_items.count %>件）</h2>
          <%= link_to(new_admin_item_path, method: :get) do %>
            <i class="fa-solid fa-circle-plus plus"></i>
          <% end %>
        </div>
      </div>
      <%= render 'admin/items/index' %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <h2>商品新規登録</h2>
      <div class="row-md-10 pb-3">
        <%= render 'layouts/errors', obj: @item_new %>
        <%= form_with model: @item_new, url: admin_items_path, local: true do |f| %>
          <div class="field d-flex mb-3">
            <div class="w-25"></div>
            <div id="preview"></div>
          </div>
          <div class="field d-flex mb-3">
            <%= f.label :image, "商品画像", class: "w-25" %><br>
            <%= f.file_field :image, accept:'image/*', id:"item-image" %>
          </div>
          <div class="field d-flex mb-3">
            <%= f.label :name, "商品名", class: "w-25" %><br>
            <%= f.text_field :name, class: "form-control w-50" %>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :introduction, "商品説明", class: "w-25" %><br>
            <%= f.text_area :introduction, class: "form-control w-50" %>
          </div>
          
          <div class="field d-flex mb-3">
            <%= f.label :detail, "詳細", class: "w-25" %><br>
            <%= f.text_area :detail, class: "form-control w-50" %>
          </div>

          <div class="field d-flex mb-3">
            <%= f.label :genre_id, "ジャンル", class: "w-25" %><br>
            <%= f.collection_select :genre_id, @genres, :id, :name, include_blank: "選択して下さい", class: "form-select w-50" %>
            <p class="m-3">ジャンルを追加する</p>
            <%= link_to  admin_genres_path do %>
              <i class="fa-solid fa-circle-plus plus"></i>
            <% end %>
          </div>
          
          <div class="field d-flex mb-3">
            <%= f.label :tag_ids, "検索用タグ", class: "w-25" %><br>
            <%= f.text_field :tag_ids, id:'tag_ids', placeholder: "タグを複数つけるには','で区切ってください。", :required => true, class: "form-control w-50" %>
          </div>
          
          <div class="d-flex flex-wrap">
            <div class="w-25 mb-3">既存のタグ一覧</div>
            <div class="w-50 mb-3">
              <% @tags.each do |tag| %>
                <i class="fa-solid fa-tag p-1 mb-3"></i><%= tag.tag_name %>
              <% end %>
            </div>  
          </div>
          
          <div class="field d-flex mb-3">
            <%= f.label :price_without_tax, "税抜価格", class: "w-25" %><br>
            <%= f.number_field :price_without_tax, class: "w-50" %>円
          </div>

          <div class="field d-flex mb-3">
            <p class="w-25">販売ステータス</p>
            <div class="is_stopped">
              <%= f.radio_button :is_stopped, false %>
              <%= f.label :is_stopped, "販売中", value: false %>

              <%= f.radio_button :is_stopped, true, class: "ml-3"%>
              <%= f.label :is_stopped, "販売停止中", value: true %>
            </div>
          </div>

          <div class="actions text-center">
            <%= f.submit "新規登録", class: 'btn btn-success w-50' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">

      <div class="row-md-10 pb-3">
        <h2>商品詳細</h2>
      </div>

      <div class="row pb-3">
        <div class="col-md-3">
          <%= image_tag @item.get_image(300, 200), class: "w-100" %>
        </div>
        <div class="col-md-7">
          <table class="table table-borderless">
            <tr>
              <th>商品名</th>
              <td><%= @item.name %></td>
            </tr>
            <tr>
              <th>商品説明</th>
              <td><%= @item.introduction %></td>
            </tr>
            <tr>
              <th>商品詳細</th>
              <td><%= @item.detail %></td>
            </tr>
            <tr>
              <th>ジャンル</th>
              <td><%= @item.genre.name %></td>
            </tr>
            <tr>
              <th>税込価格<br>(税抜価格)</th>
              <td>
                <%= @item.price_with_tax.to_s(:delimited) %>
                (<%= @item.price_without_tax.to_s(:delimited) %>)円
              </td>
            </tr>
            <tr>
              <th nowrap>販売ステータス</th>
              <% if @item.is_stopped == false %>
                <td class="text-success">販売中</td>
              <% else %>
                <td class="text-black-50">販売停止中</td>
              <% end %>
            </tr>
          </table>
          <div class="d-flex flex-wrap">
            <div class="w-25 m-3">検索用タグ</div>
            <div class="w-50 m-3">
              <% @item.tags.each do |tag| %>
                <i class="fa-solid fa-tag p-1 mb-3"></i><%= tag.tag_name %>
              <% end %>
            </div>
          </div>
          <div class="text-center mt-3">
            <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success w-50" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>