config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get '/about', to: 'homes#about', as: 'about'
    get "search" => "searches#search"
    resources :items, only: [:index,:show] do
      resource :favorites, only: [:create,:destroy]
    end
    resources :favorites, only: [:index]
    get '/users/my_page', to: 'users#show', as: 'my_page'
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all', as: 'cart_items_destroy_all'
    resources :cart_items, except: [:show,:new,:edit]
    post 'orders/confirm', to: 'orders#confirm', as: 'orders_confirm'
    get 'orders/complete', to: 'orders#complete', as: 'orders_complete'
    resources :orders, except: [:edit,:destroy]
    resources :genres, only: [:show]
    resources :tags, only: [:show]
    resources :admins, only: [:index,:show]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'users_guest_sign_in'
  end

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

# 管理者用

  namespace :admin do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :items, except: [:destroy]
    resources :genres, except: [:new,:destroy]
    resources :tags, except: [:new,:show,:destroy]
    get 'users/:id/order_history', to: 'users#order_history', as: 'users_order_history'
    patch 'users/:id/deactivate', to: 'users#deactivate', as: 'users_deactivate'
    resources :users, except: [:new,:create,:destroy]
    patch 'admins/:id/deactivate', to: 'admins#deactivate', as: 'admins_deactivate'
    resources :admins, except: [:new,:create,:destroy]
    resources :orders, only: [:index,:show,:update]
    resources :order_items, only: [:update]
  end

  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in', as: 'admins_guest_sign_in'
  end

  devise_for :admin,skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

end

app/views/admin/admins/_index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <div class="row-md-10 pb-3">
        <div class="d-flex">
          <h2 class="mr-auto">事務員一覧</h2>
          <%= link_to(new_admin_registration_path, method: :get) do %>
            <i class="fa-solid fa-circle-plus plus"></i>
          <% end %>
        </div>
        <table class="table mt-3">
          <thead style="background-color:#f5fffa">
            <tr>
              <th>
                社員ID
              </th>
              <th>
                氏名
              </th>
              <th>
                電話番号
              </th>
              <th>
                ステータス
              </th>
            </tr>
          </thead>
          <tbody>
            <% @admins.each do |admin| %>
              <tr>
                <th>
                  <%= admin.login_id %>
                </th>
                <th>
                  <%= link_to admin_admin_path(admin.id), method: :get do %>
                    <%= admin.full_name %>
                  <% end %>
                </th>
                <th>
                  <%= admin.telephone_number %>
                </th>
                <th>
                  <% if admin.is_deleted == false %>
                    有効
                  <% else %>
                    無効
                  <% end %>
                </th>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="mb-3">
          <p><%= paginate @admins %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/admins/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <h2><%= @admin.full_name %>さんの社員情報編集</h2>
      <div class="row-md-10 pb-3">
        <%= render 'layouts/errors', obj: @admin %>
        <table class="table">
          <tr>
            <th>
              社員ID
            </th>
            <th>
              <%= @admin.login_id %>
            </th>
          </tr>
          <%= form_with model: @admin, url: admin_admin_path(@admin.id), local: true, method: :patch do |form| %>
          <tr>
            <th>
              氏名
            </th>
            <th class="d-flex">
              <%= form.text_field :last_name, class: "form-control w-25 mr-3" %>
              <%= form.text_field :first_name, class: "form-control w-25 mr-3" %>
            </th>
          </tr>
          <tr>
            <th>
              フリガナ
            </th>
            <th class="d-flex">
              <%= form.text_field :last_name_kana, class: "form-control w-25 mr-3" %>
              <%= form.text_field :first_name_kana, class: "form-control w-25 mr-3" %>
            </th>
          </tr>
          <tr>
            <th>
              電話番号
            </th>
            <th>
              <%= form.text_field :telephone_number, class: "form-control w-25 mr-3" %>
            </th>
          </tr>
          <tr>
            <th>
              会員ステータス
            </th>
            <th>
              <%= form.radio_button :is_deleted, :false, {:checked => true} %>有効
            </th>
          </tr>
          <tr>
            <th>
            </th>
            <th>
              <%= form.submit "変更を保存", class: "btn btn-success w-25" %>
              <%= link_to "無効にする", admin_admins_deactivate_path, method: :patch, class: "btn btn-danger w-25" %>
            </th>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/admins/index.html.erb
<%= render 'admin/admins/index' %>

app/views/admin/admins/show.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <h2><%= @admin.full_name %>さんの社員情報詳細</h2>
      <div class="row-md-10 pb-3">
        <table class="table">
          <tr>
            <th style="width: 30%">
              社員ID
            </th>
            <th>
              <%= @admin.login_id %>
            </th>
          </tr>
          <tr>
            <th>
              氏名
            </th>
            <th>
              <%= @admin.full_name %>
            </th>
          </tr>
          <tr>
            <th>
              フリガナ
            </th>
            <th>
              <%= @admin.full_name_kana %>
            </th>
          </tr>
          <tr>
            <th>
              電話番号
            </th>
            <th>
              <%= @admin.telephone_number %>
            </th>
          </tr>
          <tr>
            <th>
              会員ステータス
            </th>
            <th>
              <% if @admin.is_deleted == false %>
                有効
              <% else %>
                無効
              <% end %>
            </th>
          </tr>
          <tr>
            <th colspan="2" class="text-center">
              <%= link_to "編集する", edit_admin_admin_path(@admin.id), class: "btn btn-success", method: :get %>
            </th>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>