config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get '/about', to: 'homes#about', as: 'about'
    get "search" => "searches#search"
    resources :items, only: [:index,:show] do
      resource :favorites, only: [:create,:destroy]
    end
    resources :favorites, only: [:index]
    get '/users/my_page', to: 'users#show', as: 'my_page'
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all', as: 'cart_items_destroy_all'
    resources :cart_items, except: [:show,:new,:edit]
    post 'orders/confirm', to: 'orders#confirm', as: 'orders_confirm'
    get 'orders/complete', to: 'orders#complete', as: 'orders_complete'
    resources :orders, except: [:edit,:destroy]
    resources :genres, only: [:show]
    resources :tags, only: [:show]
    resources :admins, only: [:index,:show]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'users_guest_sign_in'
  end

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

# 管理者用

  namespace :admin do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :items, except: [:destroy]
    resources :genres, except: [:new,:destroy]
    resources :tags, except: [:new,:show,:destroy]
    get 'users/:id/order_history', to: 'users#order_history', as: 'users_order_history'
    patch 'users/:id/deactivate', to: 'users#deactivate', as: 'users_deactivate'
    resources :users, except: [:new,:create,:destroy]
    patch 'admins/:id/deactivate', to: 'admins#deactivate', as: 'admins_deactivate'
    resources :admins, except: [:new,:create,:destroy]
    resources :orders, only: [:index,:show,:update]
    resources :order_items, only: [:update]
  end

  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in', as: 'admins_guest_sign_in'
  end

  devise_for :admin,skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:login_id]

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :login_id, uniqueness: true, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :first_name_kana, presence: true, format: { with: /\A[ァ-ヶー－]+\z/ }
  validates :telephone_number, presence: true, format: { with: /\A\d{10,11}\z/ }

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def full_name
    last_name + " " + first_name
  end

  def full_name_kana
    last_name_kana + " " + first_name_kana
  end
  
  def self.search(word)
    if word != ""
      User.where(['last_name LIKE ? OR first_name LIKE ?', "%#{word}%", "%#{word}%"])
      #部分一致で検索
    else
      User.all
    end    
  end

  def self.guest
    User.find_by(login_id: 'guest@example')
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_guest_user, except: [:index, :show, :edit]
  before_action :ensure_user, except: [:index]

  def index
    @users = User.where.not(login_id: 'guest@example').page(params[:page]).per(10)
  end

  def show

  end

  def edit

  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id)
      flash[:notice] = "編集した内容を保存しました。"
    else
      render :edit
    end
  end

  def deactivate
    @user.update(is_deleted: true)
    flash[:notice] = "無効処理を実行しました"
    redirect_to admin_users_path
  end

  def order_history
    @orders = @user.orders.order(id: "DESC").page(params[:page]).per(10)
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :login_id, :telephone_number, :is_deleted)
  end

  def ensure_user
    @user = User.find(params[:id])
  end

  def ensure_guest_user
    @admin = current_admin
    if @admin.login_id == "guest@example"
      flash[:alert] = "ゲストユーザーはアクセスできません"
      redirect_to admin_root_path
    end
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_index.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <div class="row-md-10 pb-3">
        <div class="d-flex">
          <h2 class="mr-auto">営業一覧</h2>
          <%= link_to(new_user_registration_path, method: :get) do %>
            <i class="fa-solid fa-circle-plus plus"></i>
          <% end %>
        </div>
        <table class="table mt-3 mb-5">
          <thead style="background-color:#f5fffa">
            <tr>
              <th>
                社員ID
              </th>
              <th>
                氏名
              </th>
              <th>
                電話番号
              </th>
              <th>
                ステータス
              </th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <th>
                <%= user.login_id %>
              </th>
              <th>
                <%= link_to admin_user_path(user.id), method: :get do %>
                  <%= user.full_name %>
                <% end %>
              </th>
              <th>
                <%= user.telephone_number %>
              </th>
              <th>
                <% if user.is_deleted == false %>
                  有効
                <% else %>
                  無効
                <% end %>
              </th>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="mb-3">
          <%= paginate @users %>
        </div>  
      </div>
    </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <h2><%= @user.full_name %>さんの社員情報編集</h2>
      <div class="row-md-10 pb-3">
        <%= render 'layouts/errors', obj: @user %>
        <table class="table">
          <tr>
            <th>
              社員ID
            </th>
            <th>
              <%= @user.login_id %>
            </th>
          </tr>
          <%= form_with model: @user, url: admin_user_path(@user.id), local: true, method: :patch do |form| %>
          <tr>
            <th>
              氏名
            </th>
            <th class="d-flex">
              <%= form.text_field :last_name, class: "form-control w-25 mr-3" %>
              <%= form.text_field :first_name, class: "form-control w-25 mr-3" %>
            </th>
          </tr>
          <tr>
            <th>
              フリガナ
            </th>
            <th class="d-flex">
              <%= form.text_field :last_name_kana, class: "form-control w-25 mr-3" %>
              <%= form.text_field :first_name_kana, class: "form-control w-25 mr-3" %>
            </th>
          </tr>
          <tr>
            <th>
              電話番号
            </th>
            <th>
              <%= form.text_field :telephone_number, class: "form-control w-25 mr-3" %>
            </th>
          </tr>
          <tr>
            <th>
              会員ステータス
            </th>
            <th>
              <%= form.radio_button :is_deleted, :false %>有効
            </th>
          </tr>
          <tr>
            <th>
            </th>
            <th>
              <%= form.submit "変更を保存", class: "btn btn-success w-25" %>
              <%= link_to "無効にする", admin_users_deactivate_path, method: :patch, class: "btn btn-danger w-25" %>
            </th>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<%= render 'admin/users/index' %>

app/views/admin/users/order_history.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <div class="row-md-10 pb-3">
        <h2><%= @user.full_name %>さんの注文履歴</h2>
      </div>

      <div class="row-md-10 pb-3">
        <table class="table">
          <thead class="thead-light">
            <tr>
              <th>
                購入日時
              </th>
              <th>
                注文個数
              </th>
              <th>
                注文ステータス
              </th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
            <tr>
              <th>
                <%= link_to admin_order_path(order.id) do %>
                  <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                <% end %>
              </th>
              <th>
                <%= order.order_items.sum(:amount) %>
              </th>
              <th>
                <%= order.order_status_i18n %>
              </th>
            </tr>
            <% end %>
          </tbody>
        </table>
      	<div>
          <p><%= paginate @orders %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-md-10 mx-auto">
      <h2><%= @user.full_name %>さんの社員情報詳細</h2>
      <div class="row-md-10 pb-3">
        <table class="table">
          <tr>
            <th style="width: 30%">
              社員ID
            </th>
            <th>
              <%= @user.login_id %>
            </th>
          </tr>
          <tr>
            <th>
              氏名
            </th>
            <th>
              <%= @user.full_name %>
            </th>
          </tr>
          <tr>
            <th>
              フリガナ
            </th>
            <th>
              <%= @user.full_name_kana %>
            </th>
          </tr>
          <tr>
            <th>
              電話番号
            </th>
            <th>
              <%= @user.telephone_number %>
            </th>
          </tr>
          <tr>
            <th>
              会員ステータス
            </th>
            <th>
              <% if @user.is_deleted == false %>
                有効
              <% else %>
                無効
              <% end %>
            </th>
          </tr>
          <tr></tr>
          <tr>
            <th colspan="2" class="text-center mt-5">
              <%= link_to "編集する", edit_admin_user_path(@user.id), class: "btn btn-success", method: :get %>
              <%= link_to "注文履歴一覧を見る", admin_users_order_history_path(@user.id), class: "btn btn-primary ml-5", method: :get %>
            </th>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>