config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: "homes#top"
    get '/about', to: 'homes#about', as: 'about'
    get "search" => "searches#search"
    resources :items, only: [:index,:show] do
      resource :favorites, only: [:create,:destroy]
    end
    resources :favorites, only: [:index]
    get '/users/my_page', to: 'users#show', as: 'my_page'
    delete 'cart_items/destroy_all', to: 'cart_items#destroy_all', as: 'cart_items_destroy_all'
    resources :cart_items, except: [:show,:new,:edit]
    post 'orders/confirm', to: 'orders#confirm', as: 'orders_confirm'
    get 'orders/complete', to: 'orders#complete', as: 'orders_complete'
    resources :orders, except: [:edit,:destroy]
    resources :genres, only: [:show]
    resources :tags, only: [:show]
    resources :admins, only: [:index,:show]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in', as: 'users_guest_sign_in'
  end

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

# 管理者用

  namespace :admin do
    root to: "homes#top"
    get "search" => "searches#search"
    resources :items, except: [:destroy]
    resources :genres, except: [:new,:destroy]
    resources :tags, except: [:new,:show,:destroy]
    get 'users/:id/order_history', to: 'users#order_history', as: 'users_order_history'
    patch 'users/:id/deactivate', to: 'users#deactivate', as: 'users_deactivate'
    resources :users, except: [:new,:create,:destroy]
    patch 'admins/:id/deactivate', to: 'admins#deactivate', as: 'admins_deactivate'
    resources :admins, except: [:new,:create,:destroy]
    resources :orders, only: [:index,:show,:update]
    resources :order_items, only: [:update]
  end

  devise_scope :admin do
    post 'admins/guest_sign_in', to: 'admin/sessions#guest_sign_in', as: 'admins_guest_sign_in'
  end

  devise_for :admin,skip: [:passwords], controllers: {
    registrations: "admin/registrations",
    sessions: "admin/sessions"
  }

end

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div class="row mx-auto">
    <div id="error_explanation">
      <h3 class="text-danger"><%= obj.errors.count %> 件のエラーが発生しました</h3>
      <ul class="text-danger">
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row mx-auto">
    <div id="error_explanation">
      <h3><%= obj.errors.count %> 件のエラーが発生しました</h3>
      <ul class="text-danger">
        <% obj.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class='fixed-bottom'>
  <div class='container'>
    <div class='row pt-3 '>
      <div class='mx-auto'>
        <p class='text-light'>©NoG
          <%= link_to new_admin_session_path, class: "text-light ml-2" do %>
            <i class="fa-solid fa-screwdriver-wrench"></i>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="border-bottom">
  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <div class="container">
      <% if admin_signed_in? %>
        <%= link_to image_tag("logoM.png", class:"navbar-brand"), "/admin/orders" %>
      <% elsif user_signed_in? %>
        <%= link_to image_tag("logoM.png", class:"navbar-brand"), "/items" %>
      <% else %>
        <%= link_to image_tag("logoM.png", class:"navbar-brand"), "/" %>
      <% end %>
      <% if user_signed_in? %>
        <div class="login_infomation">
          <span class="navbar-text">ログイン中：<%= current_user.full_name %></span><br>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'text-danger' %>
        </div>
      <% elsif admin_signed_in? %>
        <div class="login_infomation">
          <i class="fa-solid fa-user-tie fa-2x" style="color:#cc5264;"></i>
          <span class="navbar-text">管理者ログイン中：<%= current_admin.full_name %></span><br>
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'text-danger' %>
        </div>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li>
              <%= link_to "マイページ", my_page_path, class: 'nav-link' %>
            </li>
            <li>
              <%= link_to "商品一覧", items_path, class: 'nav-link' %>
            </li>
            <li>
              <%= link_to "カート", cart_items_path, class: 'nav-link' %>
            </li>
            <li>
              <%= link_to "事務員一覧", admins_path, class: 'nav-link' %>
            </li>
          <% elsif admin_signed_in? %>
            <li>
              <%= link_to "商品一覧", admin_items_path, class: 'nav-link' %>
            </li>
            <li>
              <%= link_to "注文履歴一覧", admin_orders_path, class: 'nav-link' %>
            </li>
            <li>
              <%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link' %>
            </li>
            <li>
              <%= link_to "営業一覧", admin_users_path, class: 'nav-link' %>
            </li>
            <li>
              <%= link_to "事務員一覧", admin_admins_path, class: 'nav-link' %>
            </li>
          <% else %>
            <li>
              <%= link_to "About", about_path, class: 'nav-link' %>
            </li>
            </li>
            <li>
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="row-md-12">
    <%= render 'layouts/search' %>
  </div>
</header>

app/views/layouts/_notice.html.erb
<% if flash[:notice] %>
  <div class="w-auto bg-success">
    <div class="container">
      <div class="row">
        <div class="col-8 mx-auto mt-2">
          <p class="text-center text-white font-weight-bold" id="notice">
            <%= flash[:notice] %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="w-auto bg-danger">
    <div class="container">
      <div class="row">
        <div class="col-8 mx-auto mt-2">
          <p class="text-center text-white font-weight-bold" id="notice">
            <%= flash[:alert] %>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form text-right mr-5">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word, value: @word, class: "mr-3" %>
      <%= f.select :range, options_for_select(["事務員", "注文", "商品"],"商品") %>
      <%= f.submit "検索", class: "btn btn-info m-2" %>
    <% end %>
  </div>
<% elsif admin_signed_in? %>
  <div class="search_form text-right mr-5">
    <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word, value: @word, class: "mr-3" %>
      <%= f.select :range, options_for_select(["事務員", "営業", "注文", "商品"],"商品") %>
      <%= f.submit "検索", class: "btn btn-info m-2" %>
    <% end %>
  </div>
<% else %>
   <div class="search_form">
   </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 p-3">
  <h3 class="border-bottom">ジャンル検索</h3>
  <% if user_signed_in? %>
    <div class="list-group list-group-flush border-bottom scrollarea">
      <div class="list-group-item list-group-item-action py-3 lh-sm">
        <span>
          <%= link_to "お気に入り商品", favorites_path, class: 'd-flex w-100 align-items-center justify-content-between' %>
        </span>
      </div>
      <% genres.each do |genre| %>
        <% if genre.items.count != 0 %>
          <div class="list-group-item list-group-item-action py-3 lh-sm">
            <span>
              <%= link_to genre.name, genre_path(genre),class: 'd-flex w-100 align-items-center justify-content-between' %>
            </span>
          </div>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="list-group list-group-flush border-bottom scrollarea">
      <% genres.each do |genre| %>
        <% if genre.items.count != 0 %>
          <div class="list-group-item list-group-item-action py-3 lh-sm">
            <span>
              <%= link_to genre.name, admin_genre_path(genre),class: 'd-flex w-100 align-items-center justify-content-between' %>
            </span>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Order_kun</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f6e922a9dc.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/notice' %>

    <%= yield %>
  </body>
  <footer>
    <%= render 'layouts/footer' %>
  </footer>
</html>